#!/bin/sh
test_anyuid() {
  for project in ${USER_PROJECTS}; do
    count_anyuid_default=`oc describe scc anyuid -n ${project} | grep "Users:.*system:serviceaccount:.*:default" | wc -l`
    assertEquals " service account default in project ${project};" 0 ${count_anyuid_default}
  done
}
suite_addTest test_anyuid
