#!/bin/sh
test_project_quotas() {
  for project in `oc get projects | grep -v "\(openshift\|kube\|default\|logging\)" | grep -v NAME | cut -d' ' -f1`; do
    limitrange=`oc get limitrange -n ${project} | grep -c "[:word:]"`
    assertNotEquals "limitrange not set in project ${project}" $limitrange 0
    resourcequota=`oc get resourcequota -n ${project} | grep -c "[:word:]"`
    assertNotEquals "resourcequota not set in project ${project}" $resourcequota 0
  done
}
. shunit2
