#!/bin/sh
test_project_quotas() {
  for project in ${USER_PROJECTS}; do
    limitrange=`oc get limitrange -n ${project} | wc -l`
    assertNotEquals " limitrange not set in project ${project};" 0 $limitrange
    resourcequota=`oc get resourcequota -n ${project} | wc -l`
    assertNotEquals " resourcequota not set in project ${project};" 0 $resourcequota
  done
}
suite_addTest test_project_quotas
