#!/bin/sh
test_nodes_ready() {
  for node in `oc get nodes | cut -d" " -f1 | tail -n +2`; do
    ready=`oc get node ${node} -o json | jq -r '.status.conditions[] | select(.type=="Ready") | .status'`
    assertEquals "node ${node} not ready" $ready "True"
  done
}
test_nodes_no_warnings() {
  for node in `oc get nodes | cut -d" " -f1 | tail -n +2`; do
    warnings=`oc describe node/${node} | grep -A64 "^Events:" | grep "Warn" | wc -l`
    assertEquals "node ${node} has warnings" 0 ${warnings}
  done
}
suite_addTest test_nodes_ready
suite_addTest test_nodes_no_warnings
