#!/bin/sh
test_nodes_ready() {
  for node in `oc get nodes | cut -d" " -f1 | tail -n +2`; do
    ready=`oc get node ${node} -o json | jq -r '.status.conditions[] | select(.type=="Ready") | .status'`
    assertEquals "node ${node} not ready" $ready "True"
  done
}
test_nodes_no_warnings() {
  for node in `oc get nodes | cut -d" " -f1 | tail -n +2`; do
    warnings=`oc describe node/${node} | grep -a64 "^Events:" | grep "Warn" | grep -c "[:word:]"`
    assertEquals "node ${node} has warnings" ${warnings} 0
  done
}
. shunit2
