#!/bin/sh
test_security_context_privileged() {
  for project in ${USER_PROJECTS}; do
    for pod in `oc get po -n ${project} | cut -d' ' -f1 | tail -n +2`; do
      count_privileged=`oc export po/${pod} -n ${project} -o json | jq -r '..|.securityContext?.privileged' | grep -c true`
      assertEquals " pod ${pod} in project ${project} runs with privileged security context;" ${count_privileged} 0
    done
  done
}
suite_addTest test_security_context_privileged
