kind: DeploymentConfig
apiVersion: v1
metadata:
  name: openshift-unit
  namespace: openshift-unit
  labels:
    app: openshift-unit
spec:
  triggers:
  - type: ConfigChange
  replicas: 1
  selector:
    app: openshift-unit
    deploymentconfig: openshift-unit
  template:
    metadata:
      labels:
        app: openshift-unit
        deploymentconfig: openshift-unit
    spec:
      serviceAccountName: openshift-unit
      serviceAccount: openshift-unit
      containers:
      - name: openshift-unit
        image: gerald1248/openshift-unit
        resources:
          limits:
            cpu: 200m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        env:
        - name: POD_NAMESPACE
          value: openshift-unit
        volumeMounts:
        - name: openshift-unit-volume
          mountPath: /etc/openshift-unit.d
      volumes:
      - name: openshift-unit-volume
        configMap:
          name: openshift-unit
