apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: openshift-unit
  namespace: openshift-unit
  labels:
    app: openshift-unit
spec:
  schedule: "10 0 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: openshift-unit
          serviceAccount: openshift-unit
          containers:
          -
            name: openshift-unit
            image: gerald1248/openshift-unit
            resources:
              limits:
                cpu: 200m
                memory: 1Gi
              requests:
                cpu: 100m
                memory: 512Mi
            args:
            - /bin/sh
            - -c
            - openshift-unit || true
            env:
            - name: POD_NAMESPACE
              value: openshift-unit
            volumeMounts:
            - name: openshift-unit-volume
              mountPath: /etc/openshift-unit.d
          volumes:
          - name: openshift-unit-volume
            configMap:
              name: openshift-unit
          restartPolicy: Never
