kind: LimitRange
apiVersion: v1
metadata:
  name: openshift-unit
  namespace: openshift-unit
  labels:
    app: openshift-unit
spec:
  limits:
  -
    type: Container
    default:
      cpu: 400m
      memory: 1Gi
    defaultRequest:
      cpu: 200m
      memory: 512Mi