kind: ResourceQuota
apiVersion: v1
metadata:
  name: openshift-unit
  namespace: openshift-unit
  labels:
    app: openshift-unit
spec:
  hard:
    pods: "4" # deployer + running pod + replacement + spare
    requests.cpu: 800m
    requests.memory: 2Gi
    limits.cpu: 1600m
    limits.memory: 4Gi