apiVersion: v1
data:
  limits_test: |
    #!/bin/sh
    test_project_quotas() {
      for project in `oc get projects | grep -v "\(openshift\|kube\|default\|logging\)" | grep -v NAME | cut -d' ' -f1`; do
        limitrange=`oc get limitrange -n ${project} | grep -c "[:word:]"`
        assertNotEquals "limitrange not set in project ${project}" $limitrange 0
        resourcequota=`oc get resourcequota -n ${project} | grep -c "[:word:]"`
        assertNotEquals "resourcequota not set in project ${project}" $resourcequota 0
      done
    }
    . shunit2
  nodes_test: |
    #!/bin/sh
    test_nodes_ready() {
      for node in `oc get nodes | cut -d" " -f1 | tail -n +2`; do
        ready=`oc get node ${node} -o json | jq -r '.status.conditions[] | select(.type=="Ready") | .status'`
        assertEquals "node ${node} not ready" $ready "True"
      done
    }
    test_nodes_no_warnings() {
      for node in `oc get nodes | cut -d" " -f1 | tail -n +2`; do
        warnings=`oc describe node/${node} | grep -a64 "^Events:" | grep "Warn" | grep -c "[:word:]"`
        assertEquals "node ${node} has warnings" ${warnings} 0
      done
    }
    . shunit2
  privileged_test: |
    #!/bin/sh
    test_security_context_privileged() {
      for project in `oc get projects | grep -v "\(openshift\|kube\|default\|logging\)" | grep -v NAME | cut -d' ' -f1`; do
        for pod in `oc get po -n ${project}`; do
          count_privileged=`oc export po/${pod} -n ${project} -o json | jq -r '..|.securityContext?.privileged' | grep -c true`
          assertEquals "pod ${pod} in project ${project} runs with privileged security context" ${count_privileged} 0
        done
      done
    }
    . shunit2
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: openshift-unit
